opt_in_rules: # some rules are only opt-in
  - empty_count
  - redundant_nil_coalescing
  - switch_case_on_newline
  - force_unwrapping
  - conditional_returns_on_newline
  - closure_spacing
  - implicitly_unwrapped_optional
  - sorted_imports
  - valid_docs
  - nslocalizedstring_require_bundle

included:
  - Sources

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Tests
  - Example

disabled_rules: # rule identifiers to exclude from running
  - trailing_whitespace
  - switch_case_on_newline

identifier_name:
  min_length: # only min_length
    - 3
    - 2
  excluded: # excluded via string array
    - id
    - on
    - cp
    - bg
    - to
    - up
    - im
    - qa

nesting:
  type_level:
    warning: 4
  statement_level:
    warning: 10

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  - 2000
  - 3000

line_length:
  - 240

function_body_length:
  - 100
  - 500

cyclomatic_complexity:
  - 20
  - 30

large_tuple:
  - 4
  - 6
